server:
  port: 8080
  servlet:
    session:
      cookie:
        name: JJAANNSESSION

spring:
  datasource:
    url: jdbc:mysql://kailoslab-dev.cluster-ctcwio5avmpb.ap-northeast-2.rds.amazonaws.com:3306/jjan?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true
    username: jjanAdmin
    password: Kailos0601!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql

webdriver:
  browser:
    driver: C:\\Users\\siyan\\workspaces\\jjan\\server\\driver\\chromedriver.exe
    path: C:\Program Files\Google\Chrome\Application\chrome.exe

kailoslab:
  download-dir: C:\\Users\\siyan\\Downloads

#logging:
#  config: classpath:logback-spring.xml

