server:
  port: 8080
  servlet:
    session:
      cookie:
        name: JJAANNSESSION
    context-path: /api/v1.0

spring:
  datasource:
    url: jdbc:mysql://kailoslab-dev.cluster-ctcwio5avmpb.ap-northeast-2.rds.amazonaws.com:3306/jjan?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true
    username: jjanAdmin
    password: Kailos0601!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    database: mysql

#logging:
#  config: classpath:logback-spring.xml

